---
http_interactions:
- request:
    method: post
    uri: http://docker-api.example.com:2376/v1.16/containers/create
  response:
    status:
      code: 201
      message: Created
    headers:
      Content-Type:
      - application/json
    body:
      encoding: ASCII-8BIT
      string: '{"Id":"7cfa712d154751a88ee29f98ac2aa0b33a705d6eb5240ee9159a3351999f9524","Warnings":null}'
    http_version: 
  recorded_at: Sat, 06 May 2017 23:52:46 GMT
recorded_with: VCR 3.0.3
